### ISSUE TITLE
Collision with Unity Firebase integration

### ISSUE THREAD

**Issue by PatrickHackett** [natmlx/NatShare#129]
NatShare includes /Plugins/Android/core-1.0.0-rc02.aar and the Firebase integration also brings in some core libraries.  1.2.0 or something.  At the gradle step, duplicate libraries are detected and the build fails.
I'm not an expert (hell, I'm not an intermediate) with Android development, so I can't explain what the problem is, but it seems that both SDKs are attempting to include the same Android libraries and I have no idea how to tell Unity or Android to not do that.

**Comment by olokobayusuf** [comment]
Hey there @PatrickHackett , thanks for opening an issue and sorry for the late response on this. NatShare includes a copy of one of the Firebase libraries, which is why there is the conflict. To resolve it, follow these steps:

1. Uninstall NatShare by removing the `"api.natsuite.natshare": ...` like in your `Packages/manifest.json`.
2. The download NatShare from GitHub (you can download the `main` branch as a ZIP file).
3. Unzip the code and place the directory inside your `Packages` folder. This effectively reinstalls NatShare as a "local package", as Unity calls it.
4. With the package now installed locally, navigate to `Plugins > Android` and delete the `core-rc.aar` library.

Let me know if you face any issues following these steps.

**Comment by PatrickHackett** [comment]
Hot dog!  That worked!
Really appreciate the response and help.  :)

**Comment by olokobayusuf** [comment]
Glad to hear it!
